spring:
  application:
    name: admin-api
  docker:
    compose:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my-pocket-webtoon
    username: manager
    password: manager0
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
server:
  port: 8080